### ISSUE TITLE
Would you help me to make it mobile touch support both android and iOS?.

### ISSUE THREAD

**Issue by nazmulkp** [FlopCoat/Rise-Up-2#1]
I am new to game development. I happy to flow your tutorial from youtube. i tried to change flowing code to make workable for mobile touch screen unfortunately failed. can you help me how can I make flowing code for mobile.

```
	private void FixedUpdate () {
        mousePos = Camera.main.ScreenToWorldPoint (Input.mousePosition);

		if (Input.GetMouseButton (0)) {
			Vector2 newPos = new Vector2 (
				Mathf.Clamp(mousePos.x + offsetClicked.x, GameManager.gm.cameraEdges.w + 0.32f, GameManager.gm.cameraEdges.y - 0.32f),
				mousePos.y + offsetClicked.y
			);

			rb.MovePosition (newPos);
			offsetReleased = newPos - (Vector2) Camera.main.transform.position;
		} //Clicked
		else {
			Vector2 newPos = new Vector2 (
				Mathf.Clamp (Camera.main.transform.position.x + offsetReleased.x, GameManager.gm.cameraEdges.w + 0.32f, GameManager.gm.cameraEdges.y - 0.32f),
				Camera.main.transform.position.y + offsetReleased.y
			);

			rb.MovePosition (newPos);
			offsetClicked = newPos - mousePos;
		} //Released
    }
```

Thanks you

**Comment by FlopCoat** [comment]
Hi Nazmul,

I hadn't tried to run the game on Android, thus I didn't know about this
problem.

Here is the fix -
http://www.mediafire.com/file/szs1uyahs99gni4/HandleMovement.cs/file

Just replace the original HandleMovement.cs with this one, should be
working fine now.

Best regards,
David

**Comment by nazmulkp** [comment]
thank you so much. it's working fine.
